version: 2
jobs:
  build-client:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          command: |
            cd frontend
            npm install
            npm run build

  build-server:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
        command: |
          cd backend
          npm install
          npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-client
      - build-server
